### ISSUE TITLE
missing source files

### ISSUE THREAD

**Issue by LuYuanGao1017** [ParastooSJ/CER#1]
can not find split.sh

**Comment by yangyangyang-github** [comment]
can not find the requirement.txt

**Comment by yangyangyang-github** [comment]
can not find ".ph"

**Comment by yangyangyang-github** [comment]
can not find the ".pth"      self.CRmodel_dir =  "../model/"+dataset+"/"+dataset+"_fold_"+category+"/CR.pth"
        self.CERmodel_dir =  "../model/"+dataset+"/"+dataset+"_fold_"+category+"/"+model_type+".pth"              not ".pth"

**Comment by yangyangyang-github** [comment]
can not find the ".pth"      self.CRmodel_dir =  "../model/"+dataset+"/"+dataset+"_fold_"+category+"/CR.pth"
        self.CERmodel_dir =  "../model/"+dataset+"/"+dataset+"_fold_"+category+"/"+model_type+".pth"              not ".pth"

**Comment by ParastooSJ** [comment]
> can not find the ".pth" self.CRmodel_dir = "../model/"+dataset+"/"+dataset+"_fold_"+category+"/CR.pth"
> self.CERmodel_dir = "../model/"+dataset+"/"+dataset+"_fold_"+category+"/"+model_type+".pth" not ".pth"
The models will be published after the paper acceptance. The runs however could be found in results folder.
